#pragma once

#ifdef __GNUC__

#undef __success
#define __success(...)

#undef __in
#define __in
#undef __out
#define __out
#undef __inout
#define __inout
#undef __in_opt
#define __in_opt
#undef __out_opt
#define __out_opt
#undef __inout_opt
#define __inout_opt

#undef __ecount
#define __ecount(...)
#undef __bcount
#define __bcount(...)
#undef __in_ecount
#define __in_ecount(...)
#undef __out_ecount
#define __out_ecount(...)
#undef __inout_ecount
#define __inout_ecount(...)
#undef __out_ecount_full
#define __out_ecount_full(...)
#undef __out_ecount_part
#define __out_ecount_part(...)
#undef __inout_ecount_part
#define __inout_ecount_part(...)
#undef __out_ecount_part_opt
#define __out_ecount_part_opt(...)
#undef __inout_ecount_part_opt
#define __inout_ecount_part_opt(...)
#undef __out_ecount_full_opt
#define __out_ecount_full_opt(...)
#undef __inout_ecount_full_opt
#define __inout_ecount_full_opt(...)
#undef __in_ecount_opt
#define __in_ecount_opt(...)
#undef __out_ecount_opt
#define __out_ecount_opt(...)
#undef __inout_ecount_opt
#define __inout_ecount_opt(...)
#undef __in_ecount_z
#define __in_ecount_z(...)
#undef __out_ecount_z
#define __out_ecount_z(...)
#undef __inout_ecount_z
#define __inout_ecount_z(...)
#undef __in_ecount_nz
#define __in_ecount_nz(...)
#undef __out_ecount_nz
#define __out_ecount_nz(...)
#undef __inout_ecount_nz
#define __inout_ecount_nz(...)
#undef __in_bcount
#define __in_bcount(...)
#undef __out_bcount
#define __out_bcount(...)
#undef __inout_bcount
#define __inout_bcount(...)
#undef __out_bcount_part
#define __out_bcount_part(...)
#undef __out_bcount_full
#define __out_bcount_full(...)
#undef __inout_bcount_part
#define __inout_bcount_part(...)
#undef __out_bcount_part_opt
#define __out_bcount_part_opt(...)
#undef __out_bcount_full_opt
#define __out_bcount_full_opt(...)
#undef __inout_bcount_part_opt
#define __inout_bcount_part_opt(...)
#undef __inout_bcount_full_opt
#define __inout_bcount_full_opt(...)
#undef __in_z
#define __in_z
#undef __out_z
#define __out_z
#undef __inout_z
#define __inout_z
#undef __in_nz
#define __in_nz
#undef __out_nz
#define __out_nz
#undef __inout_nz
#define __inout_nz
#undef __in_z_opt
#define __in_z_opt
#undef __out_z_opt
#define __out_z_opt
#undef __inout_z_opt
#define __inout_z_opt
#undef __in_nz_opt
#define __in_nz_opt
#undef __out_nz_opt
#define __out_nz_opt
#undef __inout_nz_opt
#define __inout_nz_opt
#undef __ecount_opt
#define __ecount_opt(...)
#undef __bcount_opt
#define __bcount_opt(...)
#undef __in_bcount_opt
#define __in_bcount_opt(...)
#undef __out_bcount_opt
#define __out_bcount_opt(...)
#undef __inout_bcount_opt
#define __inout_bcount_opt(...)
#undef __in_bcount_z
#define __in_bcount_z(...)
#undef __out_bcount_z
#define __out_bcount_z(...)
#undef __inout_bcount_z
#define __inout_bcount_z(...)
#undef __in_bcount_nz
#define __in_bcount_nz(...)
#undef __out_bcount_nz
#define __out_bcount_nz(...)
#undef __inout_bcount_nz
#define __inout_bcount_nz(...)
#undef __in_bcount_z_opt
#define __in_bcount_z_opt(...)
#undef __out_bcount_z_opt
#define __out_bcount_z_opt(...)
#undef __inout_bcount_z_opt
#define __inout_bcount_z_opt(...)
#undef __in_bcount_nz_opt
#define __in_bcount_nz_opt(...)
#undef __out_bcount_nz_opt
#define __out_bcount_nz_opt(...)
#undef __inout_bcount_nz_opt
#define __inout_bcount_nz_opt(...)
#undef __in_ecount_z_opt
#define __in_ecount_z_opt(...)
#undef __out_ecount_z_opt
#define __out_ecount_z_opt(...)
#undef __inout_ecount_z_opt
#define __inout_ecount_z_opt(...)
#undef __in_ecount_nz_opt
#define __in_ecount_nz_opt(...)
#undef __out_ecount_nz_opt
#define __out_ecount_nz_opt(...)
#undef __inout_ecount_nz_opt
#define __inout_ecount_nz_opt(...)
#undef _Ret_notnull_
#define _Ret_notnull_
#undef _Post_writable_byte_size_
#define _Post_writable_byte_size_(...)
#undef _Outptr_
#define _Outptr_

#endif
